apiVersion: v2
name: demo
description: A Helm umbrella chart for demo environment
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: jenkins
    version: "5.8.27"
    repository: "https://charts.jenkins.io/"
